function LoadJSCodeBlob(m,f){var k=document.createElement("script");k.src=URL.createObjectURL(m);k.onload=f;document.body.appendChild(k)}
function LoadJSCode(m,f){if(!Math.fround){console.log("optimizing out Math.fround calls");for(var k=["EMSCRIPTEN_START_ASM","EMSCRIPTEN_START_FUNCS","EMSCRIPTEN_END_FUNCS"],b=0,r=0,h=0,n=0;2>=r&&b<m.length;b++)if(47==m[b]&&47==m[b+1]&&32==m[b+2]&&String.fromCharCode.apply(null,m.subarray(b+3,b+3+k[r].length))===k[r])r++;else if(1!=r||n||61!=m[b]||"global.Math.fround;"!==String.fromCharCode.apply(null,m.subarray(b+1,b+1+19))){if(n&&40==m[b]){for(var c=0;n>c&&m[b-1-c]==m[h-c];)c++;if(c==n){var d=m[b-
1-c];if(36>d||36<d&&48>d||57<d&&65>d||90<d&&95>d||95<d&&97>d||122<d)for(;c;c--)m[b-c]=32}}}else{for(h=b-1;32!=m[h-n];)n++;n&&"var"===String.fromCharCode.apply(null,m.subarray(h-n-3,h-n))||(h=n=0)}}LoadJSCodeBlob(new Blob([m],{type:"text/javascript"}),f)}
function DecompressAndLoadFile(m,f,k){m+="gz";var b=new XMLHttpRequest;b.open("GET",m,!0);b.onprogress=k;b.responseType="arraybuffer";b.onload=function(){var r=new Uint8Array(b.response),h=(new Date).getTime(),r=pako.inflate(r),n=(new Date).getTime();console.log("Decompressed "+m+" in "+(n-h)+"ms. You can remove this delay if you configure your web server to host files using gzip compression.");f(r)};b.onerror=function(){console.log("Could not download "+m);didShowErrorMessage||0!=document.URL.indexOf("file:")||
(alert("It seems your browser does not support running Unity WebGL content from file:// urls. Please upload it to an http server, or try a different browser."),didShowErrorMessage=!0)};b.send(null)}
function LoadCompressedFile(m,f,k){if(CompressionState.current==CompressionState.Unsupported)return void DecompressAndLoadFile(m,f);if(CompressionState.current==CompressionState.Pending)return void CompressionState.pendingServerRequests.push(function(){LoadCompressedFile(m,f,k)});CompressionState.current==CompressionState.Uninitialized&&(CompressionState.current=CompressionState.Pending);var b=new XMLHttpRequest;b.open("GET",m,!0);b.responseType="arraybuffer";b.onprogress=function(m){k&&k(m);CompressionState.current==
CompressionState.Pending&&(0==b.status||200==b.status?CompressionState.Set(CompressionState.Supported):CompressionState.Set(CompressionState.Unsupported))};b.onload=function(){if(0==b.status||200==b.status){CompressionState.Set(CompressionState.Supported);var h=new Uint8Array(b.response);f(h)}else CompressionState.Set(CompressionState.Unsupported),DecompressAndLoadFile(m,f,k)};b.onerror=function(){CompressionState.Set(CompressionState.Unsupported);DecompressAndLoadFile(m,f,k)};try{b.send(null)}catch(r){CompressionState.Set(CompressionState.Unsupported),
DecompressAndLoadFile(m,f,k)}}function LoadCompressedJS(m,f){LoadCompressedFile(m,function(m){LoadJSCode(m,f)})}
function fetchRemotePackageWrapper(m,f,k,b){LoadCompressedFile(m,k,function(b){var h=f;if(b.total&&(h=b.total),b.loaded){Module.dataFileDownloads||(Module.dataFileDownloads={});Module.dataFileDownloads[m]={loaded:b.loaded,total:h};var n=h=b=0,c;for(c in Module.dataFileDownloads){var d=Module.dataFileDownloads[c];b+=d.total;h+=d.loaded;n++}b=Math.ceil(b*Module.expectedDataFileDownloads/n);Module.setStatus&&Module.setStatus("Downloading data... ("+h+"/"+b+")")}else Module.dataFileDownloads||Module.setStatus&&
Module.setStatus("Downloading data...")})}function SetIndexedDBAndLoadCompressedJS(m){SetIndexedDBAndLoadCompressedJS.called||(SetIndexedDBAndLoadCompressedJS.called=!0,Module.indexedDB=m,LoadCompressedJS(Module.codeUrl))}
function CompatibilityCheck(){hasWebGL?mobile?confirm("Please note that Unity WebGL is not currently supported on mobiles. Press Ok if you wish to continue anyway.")||window.history.back():-1==browser.indexOf("Firefox")&&-1==browser.indexOf("Chrome")&&-1==browser.indexOf("Safari")&&(confirm("Please note that your browser is not currently supported for this Unity WebGL content. Try installing Firefox, or press Ok if you wish to continue anyway.")||window.history.back()):(alert("You need a browser which supports WebGL to run this content. Try installing Firefox."),
window.history.back())}function SetFullscreen(m){if("undefined"==typeof JSEvents)return void console.log("Player not loaded yet.");var f=JSEvents.canPerformEventHandlerRequests;JSEvents.canPerformEventHandlerRequests=function(){return 1};Module.cwrap("SetFullscreen","void",["number"])(m);JSEvents.canPerformEventHandlerRequests=f}
var CompressionState={Uninitialized:0,Pending:1,Unsupported:2,Supported:3,current:0,pendingServerRequests:[],Set:function(m){if(CompressionState.current==CompressionState.Pending){CompressionState.current=m;for(m=0;m<CompressionState.pendingServerRequests.length;m++)CompressionState.pendingServerRequests[m]()}}};Module.memoryInitializerRequest={response:null,callback:null,addEventListener:function(m,f){if("load"!=m)throw"Unexpected type "+m;this.callback=f}};
try{var idb=window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB,testRequest=idb.open("/idbfs-test");testRequest.onerror=function(m){m.preventDefault();SetIndexedDBAndLoadCompressedJS()};testRequest.onsuccess=function(){testRequest.result.close();SetIndexedDBAndLoadCompressedJS(idb)};setTimeout(function(){SetIndexedDBAndLoadCompressedJS()},1E3)}catch(e$$25){SetIndexedDBAndLoadCompressedJS()}
LoadCompressedFile(Module.memUrl,function(m){Module.memoryInitializerRequest.response=m;Module.memoryInitializerRequest.callback&&Module.memoryInitializerRequest.callback()});
(function(m){"object"==typeof exports&&"undefined"!=typeof module?module.exports=m():"function"==typeof define&&define.amd?define([],m):("undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:this).pako=m()})(function(){return function f(k,b,r){function h(d,c){if(!b[d]){if(!k[d]){var B="function"==typeof require&&require;if(!c&&B)return B(d,!0);if(n)return n(d,!0);B=Error("Cannot find module '"+d+"'");throw B.code="MODULE_NOT_FOUND",B;}B=b[d]={exports:{}};
k[d][0].call(B.exports,function(b){var n=k[d][1][b];return h(n?n:b)},B,B.exports,f,k,b,r)}return b[d].exports}for(var n="function"==typeof require&&require,c=0;c<r.length;c++)h(r[c]);return h}({1:[function(f,k,b){f="undefined"!=typeof Uint8Array&&"undefined"!=typeof Uint16Array&&"undefined"!=typeof Int32Array;b.assign=function(b){for(var c=Array.prototype.slice.call(arguments,1);c.length;){var d=c.shift();if(d){if("object"!=typeof d)throw new TypeError(d+"must be non-object");for(var h in d)d.hasOwnProperty(h)&&
(b[h]=d[h])}}return b};b.shrinkBuf=function(b,c){return b.length===c?b:b.subarray?b.subarray(0,c):(b.length=c,b)};var r={arraySet:function(b,c,d,h,f){if(c.subarray&&b.subarray)return void b.set(c.subarray(d,d+h),f);for(var r=0;h>r;r++)b[f+r]=c[d+r]},flattenChunks:function(b){var c,d,h,f,r;c=h=0;for(d=b.length;d>c;c++)h+=b[c].length;r=new Uint8Array(h);c=h=0;for(d=b.length;d>c;c++)f=b[c],r.set(f,h),h+=f.length;return r}},h={arraySet:function(b,c,d,h,f){for(var r=0;h>r;r++)b[f+r]=c[d+r]},flattenChunks:function(b){return[].concat.apply([],
b)}};b.setTyped=function(f){f?(b.Buf8=Uint8Array,b.Buf16=Uint16Array,b.Buf32=Int32Array,b.assign(b,r)):(b.Buf8=Array,b.Buf16=Array,b.Buf32=Array,b.assign(b,h))};b.setTyped(f)},{}],2:[function(f,k,b){function r(b,d){if(65537>d&&(b.subarray&&c||!b.subarray&&n))return String.fromCharCode.apply(null,h.shrinkBuf(b,d));for(var f="",r=0;d>r;r++)f+=String.fromCharCode(b[r]);return f}var h=f("./common"),n=!0,c=!0;try{String.fromCharCode.apply(null,[0])}catch(d){n=!1}try{String.fromCharCode.apply(null,new Uint8Array(1))}catch(D){c=
!1}var B=new h.Buf8(256);for(f=0;256>f;f++)B[f]=252<=f?6:248<=f?5:240<=f?4:224<=f?3:192<=f?2:1;B[254]=B[254]=1;b.string2buf=function(b){var d,c,f,r,n,p=b.length,q=0;for(r=0;p>r;r++)c=b.charCodeAt(r),55296===(64512&c)&&p>r+1&&(f=b.charCodeAt(r+1),56320===(64512&f)&&(c=65536+(c-55296<<10)+(f-56320),r++)),q+=128>c?1:2048>c?2:65536>c?3:4;d=new h.Buf8(q);for(r=n=0;q>n;r++)c=b.charCodeAt(r),55296===(64512&c)&&p>r+1&&(f=b.charCodeAt(r+1),56320===(64512&f)&&(c=65536+(c-55296<<10)+(f-56320),r++)),128>c?d[n++]=
c:2048>c?(d[n++]=192|c>>>6,d[n++]=128|63&c):65536>c?(d[n++]=224|c>>>12,d[n++]=128|c>>>6&63,d[n++]=128|63&c):(d[n++]=240|c>>>18,d[n++]=128|c>>>12&63,d[n++]=128|c>>>6&63,d[n++]=128|63&c);return d};b.buf2binstring=function(b){return r(b,b.length)};b.binstring2buf=function(b){for(var c=new h.Buf8(b.length),d=0,f=c.length;f>d;d++)c[d]=b.charCodeAt(d);return c};b.buf2string=function(b,c){var d,f,h,n,p=c||b.length,q=Array(2*p);for(d=f=0;p>d;)if(h=b[d++],128>h)q[f++]=h;else if(n=B[h],4<n)q[f++]=65533,d+=
n-1;else{for(h&=2===n?31:3===n?15:7;1<n&&p>d;)h=h<<6|63&b[d++],n--;1<n?q[f++]=65533:65536>h?q[f++]=h:(h-=65536,q[f++]=55296|h>>10&1023,q[f++]=56320|1023&h)}return r(q,f)};b.utf8border=function(b,d){var c;d=d||b.length;d>b.length&&(d=b.length);for(c=d-1;0<=c&&128===(192&b[c]);)c--;return 0>c?d:0===c?d:c+B[b[c]]>d?c:d}},{"./common":1}],3:[function(f,k,b){k.exports=function(b,h,f,c){var d=65535&b|0;b=b>>>16&65535|0;for(var k=0;0!==f;){k=2E3<f?2E3:f;f-=k;do d=d+h[c++]|0,b=b+d|0;while(--k);d%=65521;b%=
65521}return d|b<<16|0}},{}],4:[function(f,k,b){k.exports={Z_NO_FLUSH:0,Z_PARTIAL_FLUSH:1,Z_SYNC_FLUSH:2,Z_FULL_FLUSH:3,Z_FINISH:4,Z_BLOCK:5,Z_TREES:6,Z_OK:0,Z_STREAM_END:1,Z_NEED_DICT:2,Z_ERRNO:-1,Z_STREAM_ERROR:-2,Z_DATA_ERROR:-3,Z_BUF_ERROR:-5,Z_NO_COMPRESSION:0,Z_BEST_SPEED:1,Z_BEST_COMPRESSION:9,Z_DEFAULT_COMPRESSION:-1,Z_FILTERED:1,Z_HUFFMAN_ONLY:2,Z_RLE:3,Z_FIXED:4,Z_DEFAULT_STRATEGY:0,Z_BINARY:0,Z_TEXT:1,Z_UNKNOWN:2,Z_DEFLATED:8}},{}],5:[function(f,k,b){var r=function(){for(var b,f=[],c=0;256>
c;c++){b=c;for(var d=0;8>d;d++)b=1&b?3988292384^b>>>1:b>>>1;f[c]=b}return f}();k.exports=function(b,f,c,d){c=d+c;for(b^=-1;c>d;d++)b=b>>>8^r[255&(b^f[d])];return-1^b}},{}],6:[function(f,k,b){k.exports=function(){this.os=this.xflags=this.time=this.text=0;this.extra=null;this.extra_len=0;this.comment=this.name="";this.hcrc=0;this.done=!1}},{}],7:[function(f,k,b){k.exports=function(b,f){var n,c,d,k,B,Q,E,L,M,H,O,p,q,R,I,w,U,v,t,a,z,J,F,x;n=b.state;c=b.next_in;F=b.input;d=c+(b.avail_in-5);k=b.next_out;
x=b.output;B=k-(f-b.avail_out);Q=k+(b.avail_out-257);E=n.dmax;L=n.wsize;M=n.whave;H=n.wnext;O=n.window;p=n.hold;q=n.bits;R=n.lencode;I=n.distcode;w=(1<<n.lenbits)-1;U=(1<<n.distbits)-1;a:do{15>q&&(p+=F[c++]<<q,q+=8,p+=F[c++]<<q,q+=8);v=R[p&w];b:for(;;){if(t=v>>>24,p>>>=t,q-=t,t=v>>>16&255,0===t)x[k++]=65535&v;else{if(!(16&t)){if(0===(64&t)){v=R[(65535&v)+(p&(1<<t)-1)];continue b}if(32&t){n.mode=12;break a}b.msg="invalid literal/length code";n.mode=30;break a}a=65535&v;(t&=15)&&(t>q&&(p+=F[c++]<<q,
q+=8),a+=p&(1<<t)-1,p>>>=t,q-=t);15>q&&(p+=F[c++]<<q,q+=8,p+=F[c++]<<q,q+=8);v=I[p&U];c:for(;;){if(t=v>>>24,p>>>=t,q-=t,t=v>>>16&255,!(16&t)){if(0===(64&t)){v=I[(65535&v)+(p&(1<<t)-1)];continue c}b.msg="invalid distance code";n.mode=30;break a}if(z=65535&v,t&=15,t>q&&(p+=F[c++]<<q,q+=8,t>q&&(p+=F[c++]<<q,q+=8)),z+=p&(1<<t)-1,z>E){b.msg="invalid distance too far back";n.mode=30;break a}if(p>>>=t,q-=t,t=k-B,z>t){if(t=z-t,t>M&&n.sane){b.msg="invalid distance too far back";n.mode=30;break a}if(v=0,J=
O,0===H){if(v+=L-t,a>t){a-=t;do x[k++]=O[v++];while(--t);v=k-z;J=x}}else if(t>H){if(v+=L+H-t,t-=H,a>t){a-=t;do x[k++]=O[v++];while(--t);if(v=0,a>H){t=H;a-=t;do x[k++]=O[v++];while(--t);v=k-z;J=x}}}else if(v+=H-t,a>t){a-=t;do x[k++]=O[v++];while(--t);v=k-z;J=x}for(;2<a;)x[k++]=J[v++],x[k++]=J[v++],x[k++]=J[v++],a-=3;a&&(x[k++]=J[v++],1<a&&(x[k++]=J[v++]))}else{v=k-z;do x[k++]=x[v++],x[k++]=x[v++],x[k++]=x[v++],a-=3;while(2<a);a&&(x[k++]=x[v++],1<a&&(x[k++]=x[v++]))}break}}break}}while(d>c&&Q>k);a=
q>>3;c-=a;q-=a<<3;b.next_in=c;b.next_out=k;b.avail_in=d>c?5+(d-c):5-(c-d);b.avail_out=Q>k?257+(Q-k):257-(k-Q);n.hold=p&(1<<q)-1;n.bits=q}},{}],8:[function(f,k,b){function r(b){return(b>>>24&255)+(b>>>8&65280)+((65280&b)<<8)+((255&b)<<24)}function h(){this.mode=0;this.last=!1;this.wrap=0;this.havedict=!1;this.total=this.check=this.dmax=this.flags=0;this.head=null;this.wnext=this.whave=this.wsize=this.wbits=0;this.window=null;this.extra=this.offset=this.length=this.bits=this.hold=0;this.distcode=this.lencode=
null;this.have=this.ndist=this.nlen=this.ncode=this.distbits=this.lenbits=0;this.next=null;this.lens=new E.Buf16(320);this.work=new E.Buf16(288);this.distdyn=this.lendyn=null;this.was=this.back=this.sane=0}function n(b){var d;return b&&b.state?(d=b.state,b.total_in=b.total_out=d.total=0,b.msg="",d.wrap&&(b.adler=1&d.wrap),d.mode=R,d.last=0,d.havedict=0,d.dmax=32768,d.head=null,d.hold=0,d.bits=0,d.lencode=d.lendyn=new E.Buf32(I),d.distcode=d.distdyn=new E.Buf32(w),d.sane=1,d.back=-1,p):q}function c(b){var d;
return b&&b.state?(d=b.state,d.wsize=0,d.whave=0,d.wnext=0,n(b)):q}function d(b,d){var a,f;return b&&b.state?(f=b.state,0>d?(a=0,d=-d):(a=(d>>4)+1,48>d&&(d&=15)),d&&(8>d||15<d)?q:(null!==f.window&&f.wbits!==d&&(f.window=null),f.wrap=a,f.wbits=d,c(b))):q}function D(b,c){var a,f;return b?(f=new h,b.state=f,f.window=null,a=d(b,c),a!==p&&(b.state=null),a):q}var B,Q,E=f("../utils/common"),L=f("./adler32"),M=f("./crc32"),H=f("./inffast"),O=f("./inftrees"),p=0,q=-2,R=1,I=852,w=592,U=!0;b.inflateReset=c;
b.inflateReset2=d;b.inflateResetKeep=n;b.inflateInit=function(b){return D(b,15)};b.inflateInit2=D;b.inflate=function(b,d){var a,c,f,h,k,l,n,g,e,w,A,s,I,u,y,C,D,Y,Z,G,P,T,K=0,N=new E.Buf8(4),$=[16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15];if(!b||!b.state||!b.output||!b.input&&0!==b.avail_in)return q;a=b.state;12===a.mode&&(a.mode=13);k=b.next_out;f=b.output;n=b.avail_out;h=b.next_in;c=b.input;l=b.avail_in;g=a.hold;e=a.bits;w=l;A=n;P=p;a:for(;;)switch(a.mode){case R:if(0===a.wrap){a.mode=13;break}for(;16>
e;){if(0===l)break a;l--;g+=c[h++]<<e;e+=8}if(2&a.wrap&&35615===g){a.check=0;N[0]=255&g;N[1]=g>>>8&255;a.check=M(a.check,N,2,0);e=g=0;a.mode=2;break}if(a.flags=0,a.head&&(a.head.done=!1),!(1&a.wrap)||(((255&g)<<8)+(g>>8))%31){b.msg="incorrect header check";a.mode=30;break}if(8!==(15&g)){b.msg="unknown compression method";a.mode=30;break}if(g>>>=4,e-=4,G=(15&g)+8,0===a.wbits)a.wbits=G;else if(G>a.wbits){b.msg="invalid window size";a.mode=30;break}a.dmax=1<<G;b.adler=a.check=1;a.mode=512&g?10:12;e=
g=0;break;case 2:for(;16>e;){if(0===l)break a;l--;g+=c[h++]<<e;e+=8}if(a.flags=g,8!==(255&a.flags)){b.msg="unknown compression method";a.mode=30;break}if(57344&a.flags){b.msg="unknown header flags set";a.mode=30;break}a.head&&(a.head.text=g>>8&1);512&a.flags&&(N[0]=255&g,N[1]=g>>>8&255,a.check=M(a.check,N,2,0));e=g=0;a.mode=3;case 3:for(;32>e;){if(0===l)break a;l--;g+=c[h++]<<e;e+=8}a.head&&(a.head.time=g);512&a.flags&&(N[0]=255&g,N[1]=g>>>8&255,N[2]=g>>>16&255,N[3]=g>>>24&255,a.check=M(a.check,N,
4,0));e=g=0;a.mode=4;case 4:for(;16>e;){if(0===l)break a;l--;g+=c[h++]<<e;e+=8}a.head&&(a.head.xflags=255&g,a.head.os=g>>8);512&a.flags&&(N[0]=255&g,N[1]=g>>>8&255,a.check=M(a.check,N,2,0));e=g=0;a.mode=5;case 5:if(1024&a.flags){for(;16>e;){if(0===l)break a;l--;g+=c[h++]<<e;e+=8}a.length=g;a.head&&(a.head.extra_len=g);512&a.flags&&(N[0]=255&g,N[1]=g>>>8&255,a.check=M(a.check,N,2,0));e=g=0}else a.head&&(a.head.extra=null);a.mode=6;case 6:if(1024&a.flags&&(s=a.length,s>l&&(s=l),s&&(a.head&&(G=a.head.extra_len-
a.length,a.head.extra||(a.head.extra=Array(a.head.extra_len)),E.arraySet(a.head.extra,c,h,s,G)),512&a.flags&&(a.check=M(a.check,c,s,h)),l-=s,h+=s,a.length-=s),a.length))break a;a.length=0;a.mode=7;case 7:if(2048&a.flags){if(0===l)break a;s=0;do G=c[h+s++],a.head&&G&&65536>a.length&&(a.head.name+=String.fromCharCode(G));while(G&&l>s);if(512&a.flags&&(a.check=M(a.check,c,s,h)),l-=s,h+=s,G)break a}else a.head&&(a.head.name=null);a.length=0;a.mode=8;case 8:if(4096&a.flags){if(0===l)break a;s=0;do G=c[h+
s++],a.head&&G&&65536>a.length&&(a.head.comment+=String.fromCharCode(G));while(G&&l>s);if(512&a.flags&&(a.check=M(a.check,c,s,h)),l-=s,h+=s,G)break a}else a.head&&(a.head.comment=null);a.mode=9;case 9:if(512&a.flags){for(;16>e;){if(0===l)break a;l--;g+=c[h++]<<e;e+=8}if(g!==(65535&a.check)){b.msg="header crc mismatch";a.mode=30;break}e=g=0}a.head&&(a.head.hcrc=a.flags>>9&1,a.head.done=!0);b.adler=a.check=0;a.mode=12;break;case 10:for(;32>e;){if(0===l)break a;l--;g+=c[h++]<<e;e+=8}b.adler=a.check=
r(g);e=g=0;a.mode=11;case 11:if(0===a.havedict)return b.next_out=k,b.avail_out=n,b.next_in=h,b.avail_in=l,a.hold=g,a.bits=e,2;b.adler=a.check=1;a.mode=12;case 12:if(5===d||6===d)break a;case 13:if(a.last){g>>>=7&e;e-=7&e;a.mode=27;break}for(;3>e;){if(0===l)break a;l--;g+=c[h++]<<e;e+=8}switch(a.last=1&g,g>>>=1,e-=1,3&g){case 0:a.mode=14;break;case 1:u=a;if(U){C=void 0;B=new E.Buf32(512);Q=new E.Buf32(32);for(C=0;144>C;)u.lens[C++]=8;for(;256>C;)u.lens[C++]=9;for(;280>C;)u.lens[C++]=7;for(;288>C;)u.lens[C++]=
8;O(1,u.lens,0,288,B,0,u.work,{bits:9});for(C=0;32>C;)u.lens[C++]=5;O(2,u.lens,0,32,Q,0,u.work,{bits:5});U=!1}u.lencode=B;u.lenbits=9;u.distcode=Q;u.distbits=5;if(a.mode=20,6===d){g>>>=2;e-=2;break a}break;case 2:a.mode=17;break;case 3:b.msg="invalid block type",a.mode=30}g>>>=2;e-=2;break;case 14:g>>>=7&e;for(e-=7&e;32>e;){if(0===l)break a;l--;g+=c[h++]<<e;e+=8}if((65535&g)!==(g>>>16^65535)){b.msg="invalid stored block lengths";a.mode=30;break}if(a.length=65535&g,g=0,e=0,a.mode=15,6===d)break a;
case 15:a.mode=16;case 16:if(s=a.length){if(s>l&&(s=l),s>n&&(s=n),0===s)break a;E.arraySet(f,c,h,s,k);l-=s;h+=s;n-=s;k+=s;a.length-=s;break}a.mode=12;break;case 17:for(;14>e;){if(0===l)break a;l--;g+=c[h++]<<e;e+=8}if(a.nlen=(31&g)+257,g>>>=5,e-=5,a.ndist=(31&g)+1,g>>>=5,e-=5,a.ncode=(15&g)+4,g>>>=4,e-=4,286<a.nlen||30<a.ndist){b.msg="too many length or distance symbols";a.mode=30;break}a.have=0;a.mode=18;case 18:for(;a.have<a.ncode;){for(;3>e;){if(0===l)break a;l--;g+=c[h++]<<e;e+=8}a.lens[$[a.have++]]=
7&g;g>>>=3;e-=3}for(;19>a.have;)a.lens[$[a.have++]]=0;if(a.lencode=a.lendyn,a.lenbits=7,T={bits:a.lenbits},P=O(0,a.lens,0,19,a.lencode,0,a.work,T),a.lenbits=T.bits,P){b.msg="invalid code lengths set";a.mode=30;break}a.have=0;a.mode=19;case 19:for(;a.have<a.nlen+a.ndist;){for(;K=a.lencode[g&(1<<a.lenbits)-1],y=K>>>24,C=65535&K,!(e>=y);){if(0===l)break a;l--;g+=c[h++]<<e;e+=8}if(16>C)g>>>=y,e-=y,a.lens[a.have++]=C;else{if(16===C){for(u=y+2;u>e;){if(0===l)break a;l--;g+=c[h++]<<e;e+=8}if(g>>>=y,e-=y,
0===a.have){b.msg="invalid bit length repeat";a.mode=30;break}G=a.lens[a.have-1];s=3+(3&g);g>>>=2;e-=2}else if(17===C){for(u=y+3;u>e;){if(0===l)break a;l--;g+=c[h++]<<e;e+=8}g>>>=y;e-=y;G=0;s=3+(7&g);g>>>=3;e-=3}else{for(u=y+7;u>e;){if(0===l)break a;l--;g+=c[h++]<<e;e+=8}g>>>=y;e-=y;G=0;s=11+(127&g);g>>>=7;e-=7}if(a.have+s>a.nlen+a.ndist){b.msg="invalid bit length repeat";a.mode=30;break}for(;s--;)a.lens[a.have++]=G}}if(30===a.mode)break;if(0===a.lens[256]){b.msg="invalid code -- missing end-of-block";
a.mode=30;break}if(a.lenbits=9,T={bits:a.lenbits},P=O(1,a.lens,0,a.nlen,a.lencode,0,a.work,T),a.lenbits=T.bits,P){b.msg="invalid literal/lengths set";a.mode=30;break}if(a.distbits=6,a.distcode=a.distdyn,T={bits:a.distbits},P=O(2,a.lens,a.nlen,a.ndist,a.distcode,0,a.work,T),a.distbits=T.bits,P){b.msg="invalid distances set";a.mode=30;break}if(a.mode=20,6===d)break a;case 20:a.mode=21;case 21:if(6<=l&&258<=n){b.next_out=k;b.avail_out=n;b.next_in=h;b.avail_in=l;a.hold=g;a.bits=e;H(b,A);k=b.next_out;
f=b.output;n=b.avail_out;h=b.next_in;c=b.input;l=b.avail_in;g=a.hold;e=a.bits;12===a.mode&&(a.back=-1);break}for(a.back=0;K=a.lencode[g&(1<<a.lenbits)-1],y=K>>>24,u=K>>>16&255,C=65535&K,!(e>=y);){if(0===l)break a;l--;g+=c[h++]<<e;e+=8}if(u&&0===(240&u)){D=y;Y=u;for(Z=C;K=a.lencode[Z+((g&(1<<D+Y)-1)>>D)],y=K>>>24,u=K>>>16&255,C=65535&K,!(e>=D+y);){if(0===l)break a;l--;g+=c[h++]<<e;e+=8}g>>>=D;e-=D;a.back+=D}if(g>>>=y,e-=y,a.back+=y,a.length=C,0===u){a.mode=26;break}if(32&u){a.back=-1;a.mode=12;break}if(64&
u){b.msg="invalid literal/length code";a.mode=30;break}a.extra=15&u;a.mode=22;case 22:if(a.extra){for(u=a.extra;u>e;){if(0===l)break a;l--;g+=c[h++]<<e;e+=8}a.length+=g&(1<<a.extra)-1;g>>>=a.extra;e-=a.extra;a.back+=a.extra}a.was=a.length;a.mode=23;case 23:for(;K=a.distcode[g&(1<<a.distbits)-1],y=K>>>24,u=K>>>16&255,C=65535&K,!(e>=y);){if(0===l)break a;l--;g+=c[h++]<<e;e+=8}if(0===(240&u)){D=y;Y=u;for(Z=C;K=a.distcode[Z+((g&(1<<D+Y)-1)>>D)],y=K>>>24,u=K>>>16&255,C=65535&K,!(e>=D+y);){if(0===l)break a;
l--;g+=c[h++]<<e;e+=8}g>>>=D;e-=D;a.back+=D}if(g>>>=y,e-=y,a.back+=y,64&u){b.msg="invalid distance code";a.mode=30;break}a.offset=C;a.extra=15&u;a.mode=24;case 24:if(a.extra){for(u=a.extra;u>e;){if(0===l)break a;l--;g+=c[h++]<<e;e+=8}a.offset+=g&(1<<a.extra)-1;g>>>=a.extra;e-=a.extra;a.back+=a.extra}if(a.offset>a.dmax){b.msg="invalid distance too far back";a.mode=30;break}a.mode=25;case 25:if(0===n)break a;if(s=A-n,a.offset>s){if(s=a.offset-s,s>a.whave&&a.sane){b.msg="invalid distance too far back";
a.mode=30;break}s>a.wnext?(s-=a.wnext,I=a.wsize-s):I=a.wnext-s;s>a.length&&(s=a.length);u=a.window}else u=f,I=k-a.offset,s=a.length;s>n&&(s=n);n-=s;a.length-=s;do f[k++]=u[I++];while(--s);0===a.length&&(a.mode=21);break;case 26:if(0===n)break a;f[k++]=a.length;n--;a.mode=21;break;case 27:if(a.wrap){for(;32>e;){if(0===l)break a;l--;g|=c[h++]<<e;e+=8}if(A-=n,b.total_out+=A,a.total+=A,A&&(b.adler=a.check=a.flags?M(a.check,f,A,k-A):L(a.check,f,A,k-A)),A=n,(a.flags?g:r(g))!==a.check){b.msg="incorrect data check";
a.mode=30;break}e=g=0}a.mode=28;case 28:if(a.wrap&&a.flags){for(;32>e;){if(0===l)break a;l--;g+=c[h++]<<e;e+=8}if(g!==(4294967295&a.total)){b.msg="incorrect length check";a.mode=30;break}e=g=0}a.mode=29;case 29:P=1;break a;case 30:P=-3;break a;case 31:return-4;default:return q}b.next_out=k;b.avail_out=n;b.next_in=h;b.avail_in=l;a.hold=g;a.bits=e;if(h=a.wsize||A!==b.avail_out&&30>a.mode&&(27>a.mode||4!==d)){h=b.output;k=b.next_out;c=A-b.avail_out;var V;l=b.state;h=(null===l.window&&(l.wsize=1<<l.wbits,
l.wnext=0,l.whave=0,l.window=new E.Buf8(l.wsize)),c>=l.wsize?(E.arraySet(l.window,h,k-l.wsize,l.wsize,0),l.wnext=0,l.whave=l.wsize):(V=l.wsize-l.wnext,V>c&&(V=c),E.arraySet(l.window,h,k-c,V,l.wnext),c-=V,c?(E.arraySet(l.window,h,k-c,c,0),l.wnext=c,l.whave=l.wsize):(l.wnext+=V,l.wnext===l.wsize&&(l.wnext=0),l.whave<l.wsize&&(l.whave+=V))),0)}return h?(a.mode=31,-4):(w-=b.avail_in,A-=b.avail_out,b.total_in+=w,b.total_out+=A,a.total+=A,a.wrap&&A&&(b.adler=a.check=a.flags?M(a.check,f,A,b.next_out-A):
L(a.check,f,A,b.next_out-A)),b.data_type=a.bits+(a.last?64:0)+(12===a.mode?128:0)+(20===a.mode||15===a.mode?256:0),(0===w&&0===A||4===d)&&P===p&&(P=-5),P)};b.inflateEnd=function(b){if(!b||!b.state)return q;var d=b.state;return d.window&&(d.window=null),b.state=null,p};b.inflateGetHeader=function(b,d){var a;return b&&b.state?(a=b.state,0===(2&a.wrap)?q:(a.head=d,d.done=!1,p)):q};b.inflateInfo="pako inflate (from Nodeca project)"},{"../utils/common":1,"./adler32":3,"./crc32":5,"./inffast":7,"./inftrees":9}],
9:[function(f,k,b){var r=f("../utils/common"),h=[3,4,5,6,7,8,9,10,11,13,15,17,19,23,27,31,35,43,51,59,67,83,99,115,131,163,195,227,258,0,0],n=[16,16,16,16,16,16,16,16,17,17,17,17,18,18,18,18,19,19,19,19,20,20,20,20,21,21,21,21,16,72,78],c=[1,2,3,4,5,7,9,13,17,25,33,49,65,97,129,193,257,385,513,769,1025,1537,2049,3073,4097,6145,8193,12289,16385,24577,0,0],d=[16,16,16,16,17,17,18,18,19,19,20,20,21,21,22,22,23,23,24,24,25,25,26,26,27,27,28,28,29,29,64,64];k.exports=function(b,f,k,E,L,M,H,O){var p,q,
R,I,w,U,v,t;I=O.bits;for(var a=0,z=0,J=0,F=0,x=0,l=0,S=0,g=p=0,e=0,W=null,A=0,s=new r.Buf16(16),l=new r.Buf16(16),X=null,u=0,a=0;15>=a;a++)s[a]=0;for(z=0;E>z;z++)s[f[k+z]]++;x=I;for(F=15;1<=F&&0===s[F];F--);if(x>F&&(x=F),0===F)return L[M++]=20971520,L[M++]=20971520,O.bits=1,0;for(J=1;F>J&&0===s[J];J++);J>x&&(x=J);for(a=p=1;15>=a;a++)if(p<<=1,p-=s[a],0>p)return-1;if(0<p&&(0===b||1!==F))return-1;l[1]=0;for(a=1;15>a;a++)l[a+1]=l[a]+s[a];for(z=0;E>z;z++)0!==f[k+z]&&(H[l[f[k+z]]++]=z);if(0===b?(W=X=H,
w=19):1===b?(W=h,A-=257,X=n,u-=257,w=256):(W=c,X=d,w=-1),e=0,z=0,a=J,I=M,l=x,S=0,R=-1,g=1<<x,E=g-1,1===b&&852<g||2===b&&592<g)return 1;for(var y=0;;){y++;U=a-S;H[z]<w?(v=0,t=H[z]):H[z]>w?(v=X[u+H[z]],t=W[A+H[z]]):(v=96,t=0);p=1<<a-S;J=q=1<<l;do q-=p,L[I+(e>>S)+q]=U<<24|v<<16|t|0;while(0!==q);for(p=1<<a-1;e&p;)p>>=1;if(0!==p?(e&=p-1,e+=p):e=0,z++,0===--s[a]){if(a===F)break;a=f[k+H[z]]}if(a>x&&(e&E)!==R){0===S&&(S=x);I+=J;l=a-S;for(p=1<<l;F>l+S&&(p-=s[l+S],!(0>=p));)l++,p<<=1;if(g+=1<<l,1===b&&852<
g||2===b&&592<g)return 1;R=e&E;L[R]=x<<24|l<<16|I-M|0}}return 0!==e&&(L[I+e]=a-S<<24|4194304),O.bits=x,0}},{"../utils/common":1}],10:[function(f,k,b){k.exports={2:"need dictionary",1:"stream end","0":"","-1":"file error","-2":"stream error","-3":"data error","-4":"insufficient memory","-5":"buffer error","-6":"incompatible version"}},{}],11:[function(f,k,b){k.exports=function(){this.input=null;this.total_in=this.avail_in=this.next_in=0;this.output=null;this.total_out=this.avail_out=this.next_out=
0;this.msg="";this.state=null;this.data_type=2;this.adler=0}},{}],"/lib/inflate.js":[function(f,k,b){function r(b,d){var c=new L(d);if(c.push(b,!0),c.err)throw c.msg;return c.result}var h=f("./zlib/inflate.js"),n=f("./utils/common"),c=f("./utils/strings"),d=f("./zlib/constants"),D=f("./zlib/messages"),B=f("./zlib/zstream"),Q=f("./zlib/gzheader"),E=Object.prototype.toString,L=function(b){var c=this.options=n.assign({chunkSize:16384,windowBits:0,to:""},b||{});c.raw&&0<=c.windowBits&&16>c.windowBits&&
(c.windowBits=-c.windowBits,0===c.windowBits&&(c.windowBits=-15));!(0<=c.windowBits&&16>c.windowBits)||b&&b.windowBits||(c.windowBits+=32);15<c.windowBits&&48>c.windowBits&&0===(15&c.windowBits)&&(c.windowBits|=15);this.err=0;this.msg="";this.ended=!1;this.chunks=[];this.strm=new B;this.strm.avail_out=0;b=h.inflateInit2(this.strm,c.windowBits);if(b!==d.Z_OK)throw Error(D[b]);this.header=new Q;h.inflateGetHeader(this.strm,this.header)};L.prototype.push=function(b,f){var k,p,q,r,B,w=this.strm,D=this.options.chunkSize;
if(this.ended)return!1;p=f===~~f?f:!0===f?d.Z_FINISH:d.Z_NO_FLUSH;"string"==typeof b?w.input=c.binstring2buf(b):"[object ArrayBuffer]"===E.call(b)?w.input=new Uint8Array(b):w.input=b;w.next_in=0;w.avail_in=w.input.length;do{if(0===w.avail_out&&(w.output=new n.Buf8(D),w.next_out=0,w.avail_out=D),k=h.inflate(w,d.Z_NO_FLUSH),k!==d.Z_STREAM_END&&k!==d.Z_OK)return this.onEnd(k),this.ended=!0,!1;w.next_out&&(0===w.avail_out||k===d.Z_STREAM_END||0===w.avail_in&&(p===d.Z_FINISH||p===d.Z_SYNC_FLUSH))&&("string"===
this.options.to?(q=c.utf8border(w.output,w.next_out),r=w.next_out-q,B=c.buf2string(w.output,q),w.next_out=r,w.avail_out=D-r,r&&n.arraySet(w.output,w.output,q,r,0),this.onData(B)):this.onData(n.shrinkBuf(w.output,w.next_out)))}while(0<w.avail_in&&k!==d.Z_STREAM_END);return k===d.Z_STREAM_END&&(p=d.Z_FINISH),p===d.Z_FINISH?(k=h.inflateEnd(this.strm),this.onEnd(k),this.ended=!0,k===d.Z_OK):p===d.Z_SYNC_FLUSH?(this.onEnd(d.Z_OK),w.avail_out=0,!0):!0};L.prototype.onData=function(b){this.chunks.push(b)};
L.prototype.onEnd=function(b){b===d.Z_OK&&("string"===this.options.to?this.result=this.chunks.join(""):this.result=n.flattenChunks(this.chunks));this.chunks=[];this.err=b;this.msg=this.strm.msg};b.Inflate=L;b.inflate=r;b.inflateRaw=function(b,c){return c=c||{},c.raw=!0,r(b,c)};b.ungzip=r},{"./utils/common":1,"./utils/strings":2,"./zlib/constants":4,"./zlib/gzheader":6,"./zlib/inflate.js":8,"./zlib/messages":10,"./zlib/zstream":11}]},{},[])("/lib/inflate.js")});
var browser=function(){var m,f=navigator.userAgent,k=f.match(/(opera|chrome|safari|firefox|msie|trident(?=\/))\/?\s*(\d+)/i)||[];return/trident/i.test(k[1])?(m=/\brv[ :]+(\d+)/g.exec(f)||[],"IE "+(m[1]||"")):"Chrome"===k[1]&&(m=f.match(/\bOPR\/(\d+)/),null!=m)?"Opera "+m[1]:(k=k[2]?[k[1],k[2]]:[navigator.appName,navigator.appVersion,"-?"],null!=(m=f.match(/version\/(\d+)/i))&&k.splice(1,1,m[1]),k.join(" "))}(),hasWebGL=function(){if(!window.WebGLRenderingContext)return 0;var m=document.createElement("canvas");
return m.getContext("webgl")||m.getContext("experimental-webgl")?1:0}(),mobile=function(m){return/(android|bb\d+|meego).+mobile|avantgo|bada\/|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i.test(m)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(m.substr(0,
4))}(navigator.userAgent||navigator.vendor||window.opera);Module.compatibilitycheck?Module.compatibilitycheck():CompatibilityCheck();var didShowErrorMessage=!1;
"function"!=typeof window.onerror&&(window.onerror=function(m,f,k){return Module.errorhandler&&Module.errorhandler(m,f,k)||(console.log("Invoking error handler due to\n"+m),"function"==typeof dump&&dump("Invoking error handler due to\n"+m),didShowErrorMessage||-1!=m.indexOf("UnknownError")||-1!=m.indexOf("Program terminated with exit(0)"))?void 0:(didShowErrorMessage=!0,-1!=m.indexOf("DISABLE_EXCEPTION_CATCHING")?void alert("An exception has occured, but exception handling has been disabled in this build. If you are the developer of this content, enable exceptions in your project's WebGL player settings to be able to catch the exception or see the stack trace."):
-1!=m.indexOf("Cannot enlarge memory arrays")?void alert("Out of memory. If you are the developer of this content, try allocating more memory to your WebGL build in the WebGL player settings."):-1!=m.indexOf("Invalid array buffer length")||-1!=m.indexOf("Invalid typed array length")||-1!=m.indexOf("out of memory")?void alert("The browser could not allocate enough memory for the WebGL content. If you are the developer of this content, try allocating less memory to your WebGL build in the WebGL player settings."):
void alert("An error occured running the Unity content on this page. See your browser's JavaScript console for more info. The error was:\n"+m))});Module.locateFile=function(m){return Module.dataUrl};Module.preRun=[];Module.postRun=[];Module.print=function(){return function(m){console.log(m)}}();Module.printErr=function(m){console.error(m)};Module.canvas=document.getElementById("canvas");Module.progress=null;
Module.setStatus=function(m){if(null==this.progress){if("function"!=typeof UnityProgress)return;this.progress=new UnityProgress(canvas)}if(Module.setStatus.last||(Module.setStatus.last={time:Date.now(),text:""}),m!==Module.setStatus.text){this.progress.SetMessage(m);var f=m.match(/([^(]+)\((\d+(\.\d+)?)\/(\d+)\)/);f&&this.progress.SetProgress(parseInt(f[2])/parseInt(f[4]));""===m&&this.progress.Clear()}};Module.totalDependencies=0;
Module.monitorRunDependencies=function(m){this.totalDependencies=Math.max(this.totalDependencies,m);Module.setStatus(m?"Preparing... ("+(this.totalDependencies-m)+"/"+this.totalDependencies+")":"All downloads complete.")};Module.setStatus("Downloading (0.0/1)");var Module;"undefined"==typeof Module&&(Module=eval("(function() { try { return Module || {} } catch(e) { return {} } })()"));Module.expectedDataFileDownloads||(Module.expectedDataFileDownloads=0,Module.finishedDataFileDownloads=0);Module.expectedDataFileDownloads++;
(function(){(function(m){function f(){function f(b,d,h,k){this.start=b;this.end=d;this.crunched=h;this.audio=k}function m(b){Module.finishedDataFileDownloads++;if(!b)throw"Loading data file failed."+Error().stack;b=new Uint8Array(b);f.prototype.byteArray=b;f.prototype.requests["/data.unity3d"].onload();f.prototype.requests["/methods_pointedto_by_uievents.xml"].onload();f.prototype.requests["/preserved_derived_types.xml"].onload();f.prototype.requests["/Il2CppData/Metadata/global-metadata.dat"].onload();
f.prototype.requests["/Resources/unity_default_resources"].onload();f.prototype.requests["/Managed/mono/2.0/machine.config"].onload();Module.removeRunDependency("datafile_webgl.data")}Module.FS_createPath("/","Il2CppData",!0,!0);Module.FS_createPath("/Il2CppData","Metadata",!0,!0);Module.FS_createPath("/","Resources",!0,!0);Module.FS_createPath("/","Managed",!0,!0);Module.FS_createPath("/Managed","mono",!0,!0);Module.FS_createPath("/Managed/mono","2.0",!0,!0);f.prototype={requests:{},open:function(b,
d){this.name=d;this.requests[d]=this;Module.addRunDependency("fp "+this.name)},send:function(){},onload:function(){var b=this.byteArray.subarray(this.start,this.end);this.finish(b)},finish:function(b){var d=this;Module.FS_createPreloadedFile(this.name,null,b,!0,!0,function(){Module.removeRunDependency("fp "+d.name)},function(){d.audio?Module.removeRunDependency("fp "+d.name):Module.printErr("Preloading file "+d.name+" failed")},!1,!0);this.requests[this.name]=null}};(new f(0,17514381,0,0)).open("GET",
"/data.unity3d");(new f(17514381,17514402,0,0)).open("GET","/methods_pointedto_by_uievents.xml");(new f(17514402,17520199,0,0)).open("GET","/preserved_derived_types.xml");(new f(17520199,19340847,0,0)).open("GET","/Il2CppData/Metadata/global-metadata.dat");(new f(19340847,20215819,0,0)).open("GET","/Resources/unity_default_resources");(new f(20215819,20243444,0,0)).open("GET","/Managed/mono/2.0/machine.config");Module.addRunDependency("datafile_webgl.data");Module.preloadResults||(Module.preloadResults=
{});Module.preloadResults[k]={fromCache:!1};b?(m(b),b=null):r=m}if("object"==typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else{if("undefined"==typeof location)throw"using preloaded data can only be done on a web page or in a web worker";encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/")}var k="webgl.data";"function"!=typeof Module.locateFilePackage||
Module.locateFile||(Module.locateFile=Module.locateFilePackage,Module.printErr("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));m="function"==typeof Module.locateFile?Module.locateFile("webgl.data"):(Module.filePackagePrefixURL||"")+"webgl.data";var b=null,r=null;fetchRemotePackageWrapper(m,20243444,function(f){r?(r(f),r=null):b=f},function(b){console.error("package error:",b)});Module.calledRun?f():(Module.preRun||
(Module.preRun=[]),Module.preRun.push(f))})()})();
